name: E2E

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
env:
  MAESTRO_VERSION: 1.39.13
  MAESTRO_CLI_NO_ANALYTICS: true
  MAESTRO_DRIVER_STARTUP_TIMEOUT: 500000

jobs:
  ios_e2e:
    name: iOS
    runs-on: macos-13

    if: ${{ github.event.workflow_run.conclusion == 'success'}}

    steps:
      - uses: actions/checkout@v3

      - name: Installing Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash # will use `MAESTRO_VERSION` from env

      - name: Installing Maestro dependencies
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Install node_modules
        run: npm install

      - name: Install Pods
        working-directory: ios
        run: pod install

      - name: Build app for simulator
        working-directory: ios
        env:
          DERIVED_DATA_PATH: "build"
        run: |
          xcrun xcodebuild \
            -scheme "iweather" \
            -workspace "iweather.xcworkspace" \
            -configuration "Release" \
            -sdk "iphonesimulator" \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath "${{ env.DERIVED_DATA_PATH }}"

          echo "Print path to *.app file"
          find "${{ env.DERIVED_DATA_PATH }}" -type d -name "*.app"
      # ^^^ Path to *.app file (based on derivedDataPath + working-directory):
      - name: Run e2e tests
        env:
          APP_PATH: "ios/build/Build/Products/Release-iphonesimulator/iweather.app" # ^^^ change this path to your *.app file
        run: |
          echo "Launching iOS Simulator"
          xcrun simctl boot "iPhone 14 Pro"

          echo "Installing app on Simulator"
          xcrun simctl install booted "${{ env.APP_PATH }}"

          echo "Running tests with Maestro"
          maestro test --include-tags=smoke maestro/ --format junit
